# This is a basic workflow to help you get started with Actions

name: TEST_UPLOAD_FILE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches: 
    - main
    - release/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Upload_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo OS ready

      # Runs a set of commands using the runners shell
      - name: Install python3 and aliyunpan
        run: |
          echo OS Ready,
          echo Update patch an.
          sudo apt update -y
          sudo apt install -y python3
          sudo pip install aliyunpan
          
      # Runs a set of commands using the runners shell   
      - name: test upload a file to aliyunpan
        run: |
          mkdir -p ~/.config/
          echo "refresh_token: '2edd50e5f46b4b45bcb51332626bfbbc'"  >  .config/aliyunpan.yaml
          aliyunpan-cli -h
          echo "start" > log.txt
          date -u >> log.txt
          aliyunpan ls >> log.txt
          aliyunpan ls
          echo "end" >> log.txt          
          ls
          echo "bye"          
